/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SeminarsRouteImport } from './routes/seminars'
import { Route as CheckoutSeminarIdRouteImport } from './routes/checkout.$seminarId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SeminarsRoute = SeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSeminarIdRoute = CheckoutSeminarIdRouteImport.update({
  id: '/checkout/$seminarId',
  path: '/checkout/$seminarId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/seminars': typeof SeminarsRoute
  '/checkout/$seminarId': typeof CheckoutSeminarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/seminars': typeof SeminarsRoute
  '/checkout/$seminarId': typeof CheckoutSeminarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/seminars': typeof SeminarsRoute
  '/checkout/$seminarId': typeof CheckoutSeminarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/pricing' | '/seminars' | '/checkout/$seminarId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/pricing' | '/seminars' | '/checkout/$seminarId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/seminars'
    | '/checkout/$seminarId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  SeminarsRoute: typeof SeminarsRoute
  CheckoutSeminarIdRoute: typeof CheckoutSeminarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seminars': {
      id: '/seminars'
      path: '/seminars'
      fullPath: '/seminars'
      preLoaderRoute: typeof SeminarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$seminarId': {
      id: '/checkout/$seminarId'
      path: '/checkout/$seminarId'
      fullPath: '/checkout/$seminarId'
      preLoaderRoute: typeof CheckoutSeminarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  SeminarsRoute: SeminarsRoute,
  CheckoutSeminarIdRoute: CheckoutSeminarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
